package palette

// DO NOT EDIT THIS FILE. This file was generated via `go generate`

import "image/color"
{{range $palette := .}}
// {{ $palette.Doc }}
var {{ $palette.Name }} = color.Palette{
{{range $i, $a := $palette.Colors}}	{{ $palette.Format $i }}{{end}}}
{{end}}